# syntax=docker/dockerfile:1
FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN chmod +x docker-entrypoint.dev.sh
EXPOSE 4200
ENTRYPOINT ["./docker-entrypoint.dev.sh"]
