spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:catalog_db;DATABASE_TO_UPPER=false;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[default_schema]": catalog_db
        format-sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    locations: classpath:db/migration/h2

app:
  cors:
    allowed-origins: "http://localhost:4200,http://frontend:4200"

logging:
  level:
    "[com.app.catalog]": DEBUG
